### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by slichtzzz**
Update Russian translation

### CODE REVIEW

**Review by novikov-alexander — APPROVED** [review]

**Comment by novikov-alexander** [comment]
@cannam I am not affiliated with this PR; I reviewed it out of curiosity as a native speaker. This translation is correct and more accurate than the existing one.

**Comment by cannam** [comment]
Thanks! I understand that there are many new strings added that were not in earlier releases. But there are surprisingly many changes to existing translation strings, as well as the new ones.

I'd love it if someone (e.g. one of you and/or original translator @prokoudine) can summarise the general principles here, e.g whether conventions have changed or we are just seeing subjective decisions that have been taken in a consistently different direction.

**Comment by prokoudine** [comment]
I only looked at some of the changes. The ones I saw are generally fine. Two minor nitpicks:

1) Please try to keep the translation shorter and more consistent, e.g. use "изменить" rather than "редактировать".

2) Please try to keep the translation technically correct, e.g. some people try to say "нормализация" (likely because it sounds like the English word "normalize),  but the actual word is "нормировка" (math function).

Again, didn't have a chance to review the entire translation update, but other than that, good job and thank you :)

**Comment by novikov-alexander** [comment]
@cannam
Many changes involve using the infinitive instead of participles or noun forms. Some of the changes have standard notations like "кГц". Some use different prepositions. Some of them are definitely subjective.
Regarding "нормировка", I partly agree with @prokoudine; however, I think "нормировка", "нормирование", and "нормализация" are all often used in modern Russian. Usually, in DAWs, it is often translated as "нормализация".

**Comment by prokoudine** [comment]
Regarding nouns to infinitives transition, I didn't have a chance to see where the change happened exactly, but there is a long-standing tradition to use nouns for dialog captions and verbs for action buttons. I hope the update conforms to that.

**Comment by slichtzzz** [comment]
Hi! Thank you for your kind remarks regarding my unsubstantial contribution. I tried to do my best to keep the old translation untouched, but in some cases morphological changes are unavoidable, since the text strings are not in line with their position in the interface.

Just a small example to prove my assertions:

[Select Audio Data Format](https://github.com/sonic-visualiser/sonic-visualiser/blob/default/i18n/sonic-visualiser_ru.ts#L487)

This string actually comes from the svgui library, where it is used as a window title.

https://code.soundsoftware.ac.uk/projects/svgui/repository/entry/widgets/CSVAudioFormatDialog.cpp#L45

The normal practice in Russian is to nominalize the Window titles, make them sound like actual titles. But the old translation is made in a form of imperative (Выбрать формат звуковых данных), which sounds quie odd. So, I changed it to the more refined form (Выбор формата звуковых данных).

For some people these changes may look "subjective", but this is how the translation is normally done. Some rules have to be followed to maintain the professional look.

Anyway, if there is a strong objection to any of the changes I made, I am ready to put it in any way you like.

**Comment by cannam** [comment]
Thanks all - this sounds like the normal level of subjective conversation around a generally acceptable translation!

@slichtzzz in the past I've normally credited translators by name in the README and UI, but you don't give a "real-world" name. How would you like to be credited?

**Comment by slichtzzz** [comment]
Oh, sorry. My real-world name is Sergey Kazorin

**Comment by cannam** [comment]
Thanks! Will merge

**Pull request merged**
